[hooks]
pre-commit = "cargo fmt --all --verbose && markdownlint-cli2 --config .markdownlint.json *.md && codespell -L crate -w src/*.rs *.md LICENSE *.toml && cargo test && cargo clippy"

[logging]
verbose = true
